"""add admin table

Revision ID: db3ea241fa80
Revises: a252d9cc57dd
Create Date: 2026-03-15 14:02:30.082310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3ea241fa80'
down_revision: Union[str, None] = 'a252d9cc57dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('admins')
    op.create_unique_constraint(None, 'game', ['id'])
    op.create_unique_constraint(None, 'leaderboard_entry', ['id'])
    op.create_unique_constraint(None, 'move', ['id'])
    op.create_unique_constraint(None, 'player', ['id'])
    op.create_unique_constraint(None, 'player_stock', ['id'])
    op.create_unique_constraint(None, 'round', ['id'])
    op.create_unique_constraint(None, 'stock', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_constraint(None, 'round', type_='unique')
    op.drop_constraint(None, 'player_stock', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'move', type_='unique')
    op.drop_constraint(None, 'leaderboard_entry', type_='unique')
    op.drop_constraint(None, 'game', type_='unique')
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tg_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admins_pkey'),
    sa.UniqueConstraint('email', name='admins_email_key'),
    sa.UniqueConstraint('tg_user_id', name='admins_tg_user_id_key')
    )
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
